In [2]:
import sys
import os
import re
curPath = os.path.abspath(os.path.dirname("sequential_model.py"))
print(curPath)
rootPath = os.path.split(curPath)[0]
print(rootPath)
sys.path.append(rootPath)

/homes/ql1220/PoseEstimate/infant-3d-pose-estimation/core
/homes/ql1220/PoseEstimate/infant-3d-pose-estimation


In [16]:
%pip install opencv-python --user

ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
You should consider upgrading via the '/vol/bitbucket/nuric/docenv/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [3]:
import networks 
import utils
from utils import datasets

ModuleNotFoundError: No module named 'torchvision.models.video'

In [25]:
file_object = open('/vol/biodata/data/human3.6m/training/S1/frames/Greeting1.54138969/frame0001.png')

In [3]:
import matplotlib.pyplot as plt 
import matplotlib.image as mpimg
from PIL import Image 
import numpy as np

In [22]:
path='/vol/biodata/data/human3.6m/training/S1/frames/Greeting1.54138969/frame'
temp = []
for i in range(1,6):
    image = Image.open(path+'{:0>4d}'.format(i)+'.png') # 用PIL中的Image.open打开图像
    image_arr = np.array(image)
    temp.append(image_arr[:,:,:,np.newaxis])
    print(image_arr.shape)

c=np.concatenate(temp, axis=3)
print(c[1,1,1,:])

(1002, 1000, 3)
(1002, 1000, 3)
(1002, 1000, 3)
(1002, 1000, 3)
(1002, 1000, 3)
[32 32 33 32 34]


In [4]:
import torch
a1=np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
a2=np.array([[[5,5,5],[6,6,6]],[[7,7,7],[8,8,8]]])
a3=np.array([[[6,2,1],[6,3,2]],[[6,4,3],[6,5,4]]])
a4=np.array([[[6,2,1],[6,3,2]],[[6,4,3],[6,5,4]]])
l=[a1,a2,a3,a4]
print(a1.shape)
arr=np.stack(l, axis=0)
print(arr.shape)
tor=torch.from_numpy(arr)
x=tor.permute(3,1,2,0)
x[0,:,:,0]

(2, 2, 3)
(4, 2, 2, 3)


tensor([[1, 2],
        [3, 4]])

In [69]:
import random
rdm=random.Random(2)
a=rdm.randint(1,1)
print(a)

1


In [77]:
s='frame100002.png'
s[5:-4]
'frame{:0>4d}'.format(100300)

'frame100300'

In [79]:
if None:
    print("1")

In [67]:

import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
for i in range(1000,1001):
    lena = mpimg.imread(path+'Greeting1.54138969/frame{:0>4d}'.format(i)+'.png') 
    plt.imshow(lena) # 显示图片
    plt.axis('off') # 不显示坐标轴
    plt.show()


cpu


FileNotFoundError: [Errno 2] No such file or directory: '/vol/biodata/data/human3.6m/training/S1/frames/Greeting1.54138969/frameGreeting1.54138969/frame1000.png'

In [90]:
frame_path='/vol/biodata/data/human3.6m/training/S1/frames/'
os.listdir(frame_path)

['Phoning1.60457274',
 'Discussion1.54138969',
 'Directions1.55011271',
 'Smoking1.55011271',
 'Phoning1.55011271',
 'Purchases1.58860488',
 'Eating2.58860488',
 'Greeting1.58860488',
 'Posing1.54138969',
 'Directions1.60457274',
 'Eating2.54138969',
 'SittingDown2.60457274',
 'Greeting1.54138969',
 'Posing1.58860488',
 'Purchases1.54138969',
 'Sitting1.60457274',
 'Discussion1.58860488',
 'SittingDown2.55011271',
 'Sitting1.55011271',
 'Sitting1.58860488',
 'Discussion1.55011271',
 'SittingDown2.58860488',
 'Directions1.54138969',
 'Posing1.60457274',
 'Smoking1.54138969',
 'Phoning1.54138969',
 'Discussion1.60457274',
 'Posing1.55011271',
 'Eating2.55011271',
 'Greeting1.55011271',
 'Smoking1.58860488',
 'Purchases1.55011271',
 'Phoning1.58860488',
 'Eating2.60457274',
 'SittingDown2.54138969',
 'Greeting1.60457274',
 'Directions1.58860488',
 'Sitting1.54138969',
 'Purchases1.60457274']

In [1]:
import torchvision.transforms as transforms
import cv2 as cv

In [10]:
IMG_EXTENSIONS = [
    '.jpg', '.JPG', '.jpeg', '.JPEG',
    '.png', '.PNG', '.ppm', '.PPM', '.bmp', '.BMP',
]


def is_image_file(filename):
    return any(filename.endswith(extension) for extension in IMG_EXTENSIONS)
def make_dataset(frame_root):
    """
        frame_path: the path of frame folder, eg: /vol/biodata/data/human3.6m/training/S1/frames/
    """
    frame_paths = []

    for subject in os.listdir(frame_root):        
        activity=re.match(r'[a-zA-Z]+',subject).group()
        video_frames=[]
        d = os.path.join(frame_root, subject)
        if not os.path.isdir(d):
            continue
        for root, _, fnames in sorted(os.walk(d)):
            for fname in fnames:
                if is_image_file(fname):
                    path = os.path.join(root, fname)
                    video_frames.append(path)
        frame_paths.append({subject:video_frames})

    return frame_paths

In [11]:
frame_root='/vol/biodata/data/human3.6m/training/'
frames=make_dataset(frame_root)

In [38]:

for k,v in frames[0].items():
    print(len(v),k)
print(frames[0]['Phoning1.60457274'])

2637 Phoning1.60457274
['/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame0187.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame0620.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame1060.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame2175.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame1873.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame1401.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame0994.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame0241.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame2514.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame2262.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame0945.png', '/vol/biodata/data/human3.6m/training/S1/frames/Phoning1.60457274/frame053

In [10]:
def make_dataset(dir):
    images = []
    assert os.path.isdir(dir), '%s is not a valid directory' % dir

    for root, _, fnames in sorted(os.walk(dir)):
        for fname in fnames:
            if is_image_file(fname):
                path = os.path.join(root, fname)
                images.append(path)

    return images

cuda


In [65]:
import re
r=re.match(r'[a-zA-Z]+','Greeting1.55011271')
print(r.group())

Greeting


In [14]:
path='/vol/biodata/data/human3.6m/training/S5/MyFeatures/ground_truth_bb/'

In [24]:
import scipy.io as io 
import h5py
mat_path='/vol/biodata/data/human3.6m/training/S1/MySegmentsMat/ground_truth_bb/'
data=h5py.File(mat_path+'Discussion.58860488.mat','r')

In [55]:
mask=data['Masks']
ref=data['#refs#']
print(data.keys())
print(mask.shape)
print(ref['0'])

<KeysViewHDF5 ['#refs#', 'Masks']>
(3852, 1)
<HDF5 dataset "0": shape (1000, 1000), type "|u1">


In [33]:
data[mask[0]]

(3852, 1) object


In [56]:
import numpy as np
print(mask[0][0])
#to print data of h5py format
print(np.array(data[mask[0][0]]))

<HDF5 object reference>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
for subject in os.listdir(path):
        d = os.path.join(path, subject)
        if not os.path.isdir(d):
            continue
        for root, _, fnames in sorted(os.walk(d)):
            print(root,fnames)
            i=i+1
            if i==2:
                break
        break
#         for fname in fnames:
#             if is_image_file(fname):
#                 path = os.path.join(root, fname)
#                 images.append(path)

In [43]:
l=['a','n','c']
if 'b' in l:
    print(l.index('b'))
else:
    print('no')

no


In [45]:
os.path.join(frame_root, 'S1', 'frames')

'/vol/biodata/data/human3.6m/training/S1/frames/S1/frames'

In [ ]:
actors=["S1","S5"]
activities = ['directions', 'discussion', 'greeting', 'posing',
                      'waiting', 'walking']
for actor in actors: # actor is in the form of 'S1','S5'
    sequences = os.listdir(os.path.join(root, actor, 'frames'))
    sequences = sorted(sequences) # like 'Phoning1.60457274'
    for activity in activities:
        activity_sequences = [s for s in sequences if s.lower().startswith(activity.lower())]
        for seq in activity_sequences:
            frames = os.listdir(os.path.join(root, actor, 'frames', seq))
            frames = [int(os.path.splitext(x)[0]) for x in frames]
            frames = sorted(frames)
            if split_sequence == 'full':
                pass
            elif split_sequence == 'first_half':
                frames = frames[:len(frames) // 2]
            elif split_sequence == 'second_half':
                frames = frames[len(frames) // 2:]
            else:
                raise ValueError()
            self.sequences.append({'frames': frames, 'actor': actor, 'activity_sequence': seq})

In [8]:
os.path.splitext('frame04509.png')[0][5:]

'04509'

In [20]:
actors=["S1","S5"]
activities = ['directions', 'discussion', 'greeting', 'posing',
                      'waiting', 'walking']
root='/vol/biodata/data/human3.6m/training'
for actor in actors: # actor is in the form of 'S1','S5'
    sequences = os.listdir(os.path.join(root, actor, 'frames'))
    sequences = sorted(sequences) # like 'Phoning1.60457274'
    for activity in activities:
        activity_sequences = [s for s in sequences if s.lower().startswith(activity.lower())]
        print(activity_sequences)
        for seq in activity_sequences:
            frames = os.listdir(os.path.join(root, actor, 'frames', seq))
            frames = [int(os.path.splitext(x)[0][5:]) for x in frames]
            frames = sorted(frames)
            print(frames)
            break
        break
    break

['Directions1.54138969', 'Directions1.55011271', 'Directions1.58860488', 'Directions1.60457274']
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 

In [23]:
print(frames[1-1:4])

[1, 2, 3, 4]


In [1]:
!pip install --upgrade spacepy

     |████████████████████████████████| 4.5 MB 10.1 MB/s eta 0:00:01
     |████████████████████████████████| 10.3 MB 32.0 MB/s eta 0:00:01
     |████████████████████████████████| 27.2 MB 15.0 MB/s eta 0:00:01
     |████████████████████████████████| 1.2 MB 97.9 MB/s eta 0:00:01
  Attempting uninstall: decorator
    Found existing installation: decorator 5.0.9
    Uninstalling decorator-5.0.9:
      Successfully uninstalled decorator-5.0.9


In [2]:
!wget -r -l1 -np -nd -nc http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/latest-release/linux/ -A cdf*-dist-all.tar.gz

--2021-06-14 19:34:40--  http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/latest-release/linux/
Resolving cdaweb.gsfc.nasa.gov (cdaweb.gsfc.nasa.gov)... 2001:4d0:2418:121::65, 169.154.154.65
Connecting to cdaweb.gsfc.nasa.gov (cdaweb.gsfc.nasa.gov)|2001:4d0:2418:121::65|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/latest-release/linux/ [following]
--2021-06-14 19:34:40--  https://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/latest-release/linux/
Connecting to cdaweb.gsfc.nasa.gov (cdaweb.gsfc.nasa.gov)|2001:4d0:2418:121::65|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4906 (4.8K) [text/html]
Saving to: ‘index.html.tmp’

index.html.tmp      100%[===================>]   4.79K  --.-KB/s    in 0s      

2021-06-14 19:34:41 (52.1 MB/s) - ‘index.html.tmp’ saved [4906/4906]

Loading robots.txt; please ignore errors.
--2021-06-14 19:34:41--  https://cdaweb.gsfc.nasa.gov/r

In [5]:
!tar xf cdf*-dist-all.tar.gz -C /vol/bitbucket/ql1220/envs/pose_ql1220/lib/python3.8/site-packages

In [7]:
!cd /vol/bitbucket/ql1220/envs/pose_ql1220/lib/python3.8/site-packages

/bin/bash: line 0: cd: cdf*dist: No such file or directory


In [16]:
import torch
os.environ["CDF_LIB"] = '/vol/bitbucket/ql1220/envs/pose_ql1220/lib/python3.8/site-packages/cdf38_0-dist/lib'
from spacepy import pycdf
target_path='/vol/biodata/data/human3.6m/training/S5/MyPoseFeatures/D2_Positions/renamed'
cdf = pycdf.CDF(os.path.join(target_path, 'Directions1.54138969.cdf'))
targets = cdf[0][0, 1, :]
#targets = targets[0, 1, :]
targets=torch.FloatTensor(targets)
target=targets.view(32,2)
print(cdf)
print(target.size())

Pose: CDF_FLOAT [1, 4973, 64]
torch.Size([32, 2])


In [8]:
path='/vol/biodata/data/human3.6m/training/S5/frames/Directions1.54138969'
frames=[]
for subject in os.listdir(path):
    frames.append(subject)


# packages in environment at /vol/bitbucket/ql1220/envs/pose_ql1220:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
_pytorch_select           0.1                       cpu_0  
anyio                     3.1.0            py38h578d9bd_0    conda-forge
argon2-cffi               20.1.0           py38h497a2fe_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
bleach                    3.3.0   

networks.py  __pycache__  sequential_model.py  test.ipynb  utils


networks.py  __pycache__  sequential_model.py  test.ipynb  utils


Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

In [2]:
!source /vol/intelpython/intelpython3/bin/activate
!conda activate /vol/bitbucket/ql1220/envs/pose_ql1220
!which python

/bin/bash: conda: command not found
/vol/bitbucket/nuric/docenv/bin/python


In [94]:
import utils.datasets as ds
activities = ['directions', 'discussion', 'greeting', 'posing',
                      'waiting', 'walking']
actors=['S%d' % i for i in [1, 5]]
h=ds.Human36M('/vol/biodata/data/human3.6m/training',activities,actors,1,None)

NameError: name 'sample_window' is not defined

In [1]:
pip install tqdm

     |████████████████████████████████| 75 kB 1.2 MB/s  eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
!conda list

# packages in environment at /vol/bitbucket/ql1220/envs/pose_ql1220:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
_pytorch_select           0.1                       cpu_0  
anyio                     3.1.0            py38h578d9bd_0    conda-forge
argon2-cffi               20.1.0           py38h497a2fe_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
bleach                    3.3.0   

In [1]:
import sys
import os
import re
from utils import datasets as ds
curPath = os.path.abspath(os.path.dirname("sequential_model.py"))
print(curPath)
rootPath = os.path.split(curPath)[0]
print(rootPath)
sys.path.append(rootPath)

/homes/ql1220/PoseEstimate/infant-3d-pose-estimation/core
/homes/ql1220/PoseEstimate/infant-3d-pose-estimation


In [2]:
import torchvision.transforms as transforms
from PIL import Image 
import numpy as np
import torch
from tqdm import tqdm
import random
trans=transforms.Compose([
        transforms.Resize((384,384)),
        transforms.CenterCrop((256,256)),
        transforms.ToTensor()
    ])
def get_single(path,sequence):
    sequence_paths=os.path.join(path, sequence['actor'], 'frames', sequence['activity_sequence'])
    frames=[]
    f=[]
    for frame_num in tqdm(sequence['frames']):
        if frame_num>20:
            break
        frame_path=os.path.join(sequence_paths,'frame{:0>4d}'.format(frame_num)+'.png')
        img = Image.open(frame_path)
        img_tensor=trans(img)
        f.append(img_tensor)
    frames_torch=torch.stack(f)
    frames_torch=frames_torch.permute(1,2,3,0) #[C,H,W,sequence_length]

    return (frames_torch)

In [3]:
def get_random_frame(path,sequence,transforms):
        rnd = random.Random(1)
        frame2_num=rnd.randint(1,len(sequence['frames']))
        sequence_paths=os.path.join(path, sequence['actor'], 'frames', sequence['activity_sequence'])
        frame2_path=os.path.join(sequence_paths,'frame{:0>4d}'.format(frame2_num)+'.png')
        frame2 = Image.open(frame2_path)
        frame2_size= np.array(frame2).shape #(H,W,C)
        frame2_torch=transforms(frame2) 
        return frame2_torch,frame2_num,frame2_size

In [4]:
path='/vol/biodata/data/human3.6m/training'
frames = os.listdir(os.path.join(path, 'S1', 'frames','Phoning1.60457274'))
frames = [int(x[5:-4]) for x in frames] # like 'frame0001', take last 4 number
frames = sorted(frames) # sorted int value
sequences={ 'actor': "S1", 'activity_sequence': 'Sitting1.55011271', 'frames': frames}

In [5]:
torch1=get_single(path,sequences)

  1%|          | 20/2637 [00:02<04:31,  9.62it/s]


In [74]:
frame2,num,f=get_random_frame(path,sequences,trans)

In [76]:
f[0]

1000

In [34]:
print(torch1.size())
print(frame2.size())

torch.Size([3, 256, 256, 20])
torch.Size([3, 256, 256])


In [51]:
l=torch.stack(torch2)

In [52]:
l=l.permute(1,2,3,0)
l.size()

torch.Size([3, 256, 256, 20])

In [102]:
os.environ["CDF_LIB"] = '/vol/bitbucket/ql1220/envs/pose_ql1220/lib/python3.8/site-packages/cdf38_0-dist/lib'
from spacepy import pycdf
cdf_file = os.path.join(path, sequences['actor'], 'MyPoseFeatures/D2_Positions/renamed', sequences['activity_sequence'] + '.cdf')
cdf =pycdf.CDF(cdf_file)
pose2pose=[]
for i in range(1):
    cdf_t=cdf[0][0, i, :]
    pose_trans=torch.FloatTensor(cdf_t).view(32,2)
    pose_trans[:,0]=pose_trans[:,0]*0.384
    pose_trans[:,1]=pose_trans[:,1]*0.384
    pose2pose.append(pose_trans)


AttributeError: 'list' object has no attribute 'size'

In [100]:
import matplotlib.pyplot as plt

img=l[:,:,:,0].permute(1,2,0)
image=img.numpy()
plt.figure()
plt.scatter(pose2pose[:,0],pose2pose[:,1])
plt.imshow(image)


TypeError: list indices must be integers or slices, not tuple

<Figure size 432x288 with 0 Axes>

In [81]:
l1=[1,2]
li=[i for i in l1]

In [82]:
[0,1,2,3,6,7,8,12,13,14,15,17,18,19,25,26,27]

[1, 2]

In [16]:
os.environ["CDF_LIB"] = '/vol/bitbucket/ql1220/envs/pose_ql1220/lib/python3.8/site-packages/cdf38_0-dist/lib'
from spacepy import pycdf
path='/vol/biodata/data/human3.6m/training/S1/MyPoseFeatures/D3_Positions_mono/renamed'
cdf_file = os.path.join(path,'Phoning1.60457274.cdf')
cdf =pycdf.CDF(cdf_file)[0][0,1,:]
cdf=torch.FloatTensor(cdf).reshape(32,3)
print(cdf.size())

torch.Size([2, 3])


In [8]:
l=[1,2,3,4,5,6,7,8,9]
print(l[0],l[-1])
print(l[0:3])

1 9
[1, 2, 3]


In [9]:
import numpy
import torch
t=numpy.array(l)
t=torch.FloatTensor(t)

0
1
2
3
4
5
6
7
8
9


In [6]:
import torch

tensor=torch.FloatTensor([2.5])
tensor1 = (tensor + 1) / 2
tensor2=torch.true_divide(tensor+1,2)
print(tensor1,tensor2)

tensor([1.7500]) tensor([1.7500])
